import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getSchema } from '@tiptap/core';
import { defaultExtensions } from '../extensions';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const extensions = Object.values(defaultExtensions);

/**
 * Type hints registry for common attribute patterns.
 */
const ATTRIBUTE_TYPE_HINTS: Record<string, string> = {
  // Image
  src: 'string',
  alt: 'string',
  width: 'number | string | null',
  height: 'number | string | null',

  // Link
  href: 'string',
  target: '\'_self\' | \'_blank\' | \'_parent\' | \'_top\' | null',
  rel: 'string | null',
  linktype: '\'url\' | \'story\' | \'asset\' | \'email\'',
  uuid: 'string | null',
  anchor: 'string | null',

  // Text
  textAlign: '\'left\' | \'center\' | \'right\' | \'justify\' | null',
  level: '1 | 2 | 3 | 4 | 5 | 6',

  // Table
  colspan: 'number',
  rowspan: 'number',
  colwidth: 'number[] | null',
  backgroundColor: 'string | null',

  // Common
  id: 'string | null',
  class: 'string | null',
  title: 'string | null',

  // Emoji
  name: 'string | null',
  emoji: 'string | null',
  fallbackImage: 'string | null',

  // Color
  color: 'string | null',

  // List
  order: 'number',
  start: 'number',

  // Blok
  body: 'SbBlokData[]',

  // Image meta
  source: 'string | null',
  copyright: 'string | null',
  meta_data: 'Record<string, any> | null',
};

/**
 * Get attribute type (simple version)
 */
function getAttributeType(attrName: string): string {
  if (ATTRIBUTE_TYPE_HINTS[attrName]) {
    return ATTRIBUTE_TYPE_HINTS[attrName];
  }

  return 'unknown';
}

/**
 * Generate JSDoc comment for an attribute
 */
function generateAttrJSDoc(attrName: string): string {
  const docs: Record<string, string> = {
    level: 'Heading level (1-6)',
    textAlign: 'Text alignment direction',
    href: 'Link URL or path',
    target: 'Link target window',
    linktype: 'Type of link (url, story, asset, email)',
    uuid: 'Storyblok story UUID for internal links',
    anchor: 'Anchor/hash for the link',
    colspan: 'Number of columns this cell spans',
    rowspan: 'Number of rows this cell spans',
    colwidth: 'Column width(s) in pixels',
    backgroundColor: 'Background color (CSS color string)',
    src: 'Image source URL',
    alt: 'Alternative text for accessibility',
    class: 'CSS class name(s)',
    id: 'Element ID',
    body: 'Array of nested Storyblok components',
    emoji: 'Emoji character',
    name: 'Emoji name/identifier',
    fallbackImage: 'Fallback image URL for emoji',
    color: 'Text or highlight color',
  };

  const doc = docs[attrName];
  if (doc) {
    return `    /** ${doc} */\n`;
  }

  return '';
}

/**
 * Generate attribute interface body
 */
function generateAttributes(types: Record<string, any>) {
  let out = '';

  for (const [name, type] of Object.entries(types)) {
    const attrs = type.attrs;

    if (!attrs || Object.keys(attrs).length === 0) {
      out += `  ${name}: Record<string, never>;\n`;
      continue;
    }

    out += `  ${name}: {\n`;

    for (const [attrName, attrVal] of Object.entries(attrs)) {
      const attribute: any = attrVal;

      const hasDefault = attribute.hasDefault;
      const isRequired = attribute.isRequired;

      const typeStr = getAttributeType(attrName);
      const optional = hasDefault && !isRequired;

      out += generateAttrJSDoc(attrName);
      out += `    ${attrName}${optional ? '?' : ''}: ${typeStr};\n`;
    }

    out += `  };\n`;
  }

  return out;
}

function generateTypes() {
  const schema = getSchema(extensions as any);

  let output = `// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.\n`;
  output += `// Generated by: pnpm generate-types\n\n`;
  output += `import type { ParsedDOMSpec, PMMark, PMNode, SbBlokData } from './types';\n\n`;

  // Node attributes
  output += `/** Attribute types for all Tiptap node extensions */\n`;
  output += `export interface TiptapNodeAttributes {\n`;
  output += generateAttributes(schema.nodes);
  output += `}\n\n`;

  // Mark attributes
  output += `/** Attribute types for all Tiptap mark extensions */\n`;
  output += `export interface TiptapMarkAttributes {\n`;
  output += generateAttributes(schema.marks);
  output += `}\n\n`;

  // Helpers
  output += `export type TiptapNodeName = keyof TiptapNodeAttributes;\n`;
  output += `export type TiptapMarkName = keyof TiptapMarkAttributes;\n`;
  output += `export type TiptapComponentName = TiptapNodeName | TiptapMarkName;\n`;
  output += `export type TiptapAllAttributes = TiptapNodeAttributes & TiptapMarkAttributes;\n\n`;

  // Component props
  output += `export interface RichTextComponentProps<T extends TiptapComponentName> {
  attrs: T extends TiptapNodeName
    ? TiptapNodeAttributes[T]
    : T extends TiptapMarkName
      ? TiptapMarkAttributes[T]
      : Record<string, any>;

  parsedDOM: ParsedDOMSpec | null;

  node?: T extends TiptapNodeName ? PMNode : undefined;
  mark?: T extends TiptapMarkName ? PMMark : undefined;
}\n`;

  const outPath = path.join(
    __dirname,
    './tiptap-schema.generated.ts',
  );

  fs.writeFileSync(outPath, output, 'utf-8');

  console.warn('Generated Tiptap schema types:');
  console.warn({
    nodes: Object.keys(schema.nodes).length,
    marks: Object.keys(schema.marks).length,
    output: outPath,
  });
}

generateTypes();
