import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getSchema } from '@tiptap/core';
import type { AnyExtension } from '@tiptap/core';
import { defaultExtensions } from '../extensions';
import { parseDOMSpec } from './parseDOMSpec';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const extensions = Object.values(defaultExtensions);

/**
 * Known dynamic resolvers (hand-written, minimal set)
 * These handle cases where toDOM depends on attrs
 */
const DYNAMIC_NODE_RESOLVERS: Record<string, string> = {
  heading: `(attrs: TiptapNodeAttributes['heading']) => \`h\${attrs?.level || 1}\``,
};

/**
 * Safely create mock attrs using schema defaults
 */
function getMockAttrs(type: any) {
  const result: Record<string, any> = {};

  for (const [key, val] of Object.entries(type.attrs || {})) {
    const attr: any = val;
    result[key] = attr.default ?? null;
  }

  return result;
}

/**
 * Extract DOM spec from a node/mark
 */
function extractDOMSpec(type: any) {
  if (!type?.spec?.toDOM) {
    return null;
  }

  try {
    const mock = { type, attrs: getMockAttrs(type) };

    const dom = type.spec.toDOM(mock);
    const parsed = parseDOMSpec(dom);

    return parsed;
  }
  catch {
    return null;
  }
}

/**
 * Generate render map entries
 */
function generateRenderEntries(
  types: Record<string, any>,
  kind: 'node' | 'mark',
) {
  let out = '';

  for (const [name, type] of Object.entries(types)) {
    // Handle known dynamic nodes first (e.g. heading)
    if (kind === 'node' && DYNAMIC_NODE_RESOLVERS[name]) {
      out += `  ${name}: {
    resolve: ${DYNAMIC_NODE_RESOLVERS[name].toString()},
  },\n`;
      continue;
    }

    const spec = extractDOMSpec(type);

    if (!spec) {
      out += `  ${name}: null,\n`;
      continue;
    }

    const specStr = JSON.stringify(spec, null, 2);
    out += `  ${name}: {
        spec: ${specStr}
    },\n`;
  }

  return out;
}

/**
 * Main generator
 */
function generateRenderMap() {
  const schema = getSchema(extensions as AnyExtension[]);

  let output = `import type { TiptapNodeAttributes } from './index';\n`;
  output += `// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.\n`;
  output += `// Generated by: pnpm generate-render-map\n\n`;

  output += `/**
 * Render config for Tiptap nodes
 */
export const NODE_RENDER_MAP = {\n`;
  output += generateRenderEntries(schema.nodes, 'node');
  output += `} as const;\n\n`;

  output += `/**
 * Render config for Tiptap marks
 */
export const MARK_RENDER_MAP = {\n`;
  output += generateRenderEntries(schema.marks, 'mark');
  output += `} as const;\n\n`;

  output += `export type NodeRenderMap = typeof NODE_RENDER_MAP;\n`;
  output += `export type MarkRenderMap = typeof MARK_RENDER_MAP;\n`;

  const outPath = path.join(
    __dirname,
    './tiptap-render-map.generated.ts',
  );

  fs.writeFileSync(outPath, output, 'utf-8');

  console.warn('Generated render maps:');
  console.warn({
    nodes: Object.keys(schema.nodes).length,
    marks: Object.keys(schema.marks).length,
    output: outPath,
  });
}

generateRenderMap();
