import type { TiptapNodeAttributes } from './index';
// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by: pnpm generate-render-map

/**
 * Render config for Tiptap nodes
 */
export const NODE_RENDER_MAP = {
  paragraph: {
    spec: {
      tag: 'p',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  doc: null,
  text: null,
  blockquote: {
    spec: {
      tag: 'blockquote',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  heading: {
    resolve: (attrs: TiptapNodeAttributes['heading']) => `h${attrs?.level || 1}`,
  },
  bullet_list: {
    spec: {
      tag: 'ul',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  ordered_list: {
    spec: {
      tag: 'ol',
      attrs: {
        order: 1,
      },
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  list_item: {
    spec: {
      tag: 'li',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  code_block: {
    spec: {
      tag: 'pre',
      attrs: {},
      hasHole: true,
      children: [
        {
          tag: 'code',
          attrs: {},
          hasHole: true,
          children: [
            {
              hole: true,
            },
          ],
        },
      ],
    },
  },
  hard_break: {
    spec: {
      tag: 'br',
      attrs: {},
      hasHole: false,
      children: [],
    },
  },
  horizontal_rule: {
    spec: {
      tag: 'hr',
      attrs: {},
      hasHole: false,
      children: [],
    },
  },
  image: {
    spec: {
      tag: 'img',
      attrs: {},
      hasHole: false,
      children: [],
    },
  },
  emoji: {
    spec: {
      tag: 'span',
      attrs: {
        'data-type': 'emoji',
      },
      hasHole: false,
      children: [
        {
          tag: 'img',
          attrs: {
            style: 'width: 1.25em; height: 1.25em; vertical-align: text-top',
            draggable: 'false',
            loading: 'lazy',
          },
          hasHole: false,
          children: [],
        },
      ],
    },
  },
  table: {
    spec: {
      tag: 'table',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  tableRow: {
    spec: {
      tag: 'tr',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  tableCell: {
    spec: {
      tag: 'td',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  tableHeader: {
    spec: {
      tag: 'th',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  blok: {
    spec: {
      tag: 'span',
      attrs: {
        'data-blok': 'null',
        'style': 'display: none',
      },
      hasHole: false,
      children: [],
    },
  },
  details: {
    spec: {
      tag: 'details',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  detailsContent: {
    spec: {
      tag: 'div',
      attrs: {
        'data-type': 'detailsContent',
      },
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  detailsSummary: {
    spec: {
      tag: 'summary',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
} as const;

/**
 * Render config for Tiptap marks
 */
export const MARK_RENDER_MAP = {
  link: {
    spec: {
      tag: 'a',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  bold: {
    spec: {
      tag: 'strong',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  italic: {
    spec: {
      tag: 'em',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  strike: {
    spec: {
      tag: 's',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  underline: {
    spec: {
      tag: 'u',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  code: {
    spec: {
      tag: 'code',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  superscript: {
    spec: {
      tag: 'sup',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  subscript: {
    spec: {
      tag: 'sub',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  highlight: {
    spec: {
      tag: 'mark',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  textStyle: {
    spec: {
      tag: 'span',
      attrs: {
        style: 'color: null',
      },
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  anchor: {
    spec: {
      tag: 'span',
      attrs: {
        id: null,
      },
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  styled: {
    spec: {
      tag: 'span',
      attrs: {},
      hasHole: true,
      children: [
        {
          hole: true,
        },
      ],
    },
  },
  reporter: null,
} as const;

export type NodeRenderMap = typeof NODE_RENDER_MAP;
export type MarkRenderMap = typeof MARK_RENDER_MAP;
