import { BridgeLoader } from "@/components/BridgeLoader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <BridgeLoader />
        {children}
      </body>
    </html>
  );
}
