packages:
  - packages/*
  - packages/*/playground
  - packages/*/playground/*
  - tools/*
catalog:
  "@types/react": 19.2.3
  "@types/react-dom": 19.2.3
  jiti: 2.7.0

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

onlyBuiltDependencies:
  - cypress
  - esbuild
