// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by: pnpm generate-types

import type { ParsedDOMSpec, PMMark, PMNode, SbBlokData } from './types';

/** Attribute types for all Tiptap node extensions */
export interface TiptapNodeAttributes {
  paragraph: {
    /** Text alignment direction */
    textAlign?: 'left' | 'center' | 'right' | 'justify' | null;
  };
  doc: Record<string, never>;
  text: Record<string, never>;
  blockquote: Record<string, never>;
  heading: {
    /** Text alignment direction */
    textAlign?: 'left' | 'center' | 'right' | 'justify' | null;
    /** Heading level (1-6) */
    level?: 1 | 2 | 3 | 4 | 5 | 6;
  };
  bullet_list: Record<string, never>;
  ordered_list: {
    order?: number;
  };
  list_item: Record<string, never>;
  code_block: {
    language?: unknown;
  };
  hard_break: Record<string, never>;
  horizontal_rule: Record<string, never>;
  image: {
    /** Image source URL */
    src?: string;
    /** Alternative text for accessibility */
    alt?: string;
    title?: string | null;
    width?: number | string | null;
    height?: number | string | null;
  };
  emoji: {
    /** Emoji name/identifier */
    name?: string | null;
  };
  table: Record<string, never>;
  tableRow: Record<string, never>;
  tableCell: {
    /** Number of columns this cell spans */
    colspan?: number;
    /** Number of rows this cell spans */
    rowspan?: number;
    /** Column width(s) in pixels */
    colwidth?: number[] | null;
  };
  tableHeader: {
    /** Number of columns this cell spans */
    colspan?: number;
    /** Number of rows this cell spans */
    rowspan?: number;
    /** Column width(s) in pixels */
    colwidth?: number[] | null;
  };
  blok: {
    /** Element ID */
    id?: string | null;
    /** Array of nested Storyblok components */
    body?: SbBlokData[];
  };
  details: Record<string, never>;
  detailsContent: Record<string, never>;
  detailsSummary: Record<string, never>;
}

/** Attribute types for all Tiptap mark extensions */
export interface TiptapMarkAttributes {
  link: {
    /** Link URL or path */
    href?: string;
    /** Storyblok story UUID for internal links */
    uuid?: string | null;
    /** Anchor/hash for the link */
    anchor?: string | null;
    /** Link target window */
    target?: '_self' | '_blank' | '_parent' | '_top' | null;
    /** Type of link (url, story, asset, email) */
    linktype?: 'url' | 'story' | 'asset' | 'email';
  };
  bold: Record<string, never>;
  italic: Record<string, never>;
  strike: Record<string, never>;
  underline: Record<string, never>;
  code: Record<string, never>;
  superscript: Record<string, never>;
  subscript: Record<string, never>;
  highlight: Record<string, never>;
  textStyle: {
    /** CSS class name(s) */
    class?: string | null;
    /** Element ID */
    id?: string | null;
    /** Text or highlight color */
    color?: string | null;
  };
  anchor: {
    /** Element ID */
    id?: string | null;
  };
  styled: {
    /** CSS class name(s) */
    class?: string | null;
  };
  reporter: Record<string, never>;
}

export type TiptapNodeName = keyof TiptapNodeAttributes;
export type TiptapMarkName = keyof TiptapMarkAttributes;
export type TiptapComponentName = TiptapNodeName | TiptapMarkName;
export type TiptapAllAttributes = TiptapNodeAttributes & TiptapMarkAttributes;

export interface RichTextComponentProps<T extends TiptapComponentName> {
  attrs: T extends TiptapNodeName
    ? TiptapNodeAttributes[T]
    : T extends TiptapMarkName
      ? TiptapMarkAttributes[T]
      : Record<string, any>;

  parsedDOM: ParsedDOMSpec | null;

  node?: T extends TiptapNodeName ? PMNode : undefined;
  mark?: T extends TiptapMarkName ? PMMark : undefined;
}
