// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokRichtext, StoryblokMultiasset, StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface ArticleOverviewPage {
  meta_title?: string;
  meta_description?: string;
  headline?: string;
  component: "article-overview-page";
  _uid: string;
  [k: string]: unknown;
}

export interface ArticlePage {
  headline?: string;
  image?: StoryblokAsset;
  text?: StoryblokRichtext;
  call_to_action?: (ISbStoryData<Banner> | string)[];
  categories?: (ISbStoryData<Category> | string)[];
  meta_title?: string;
  meta_description?: string;
  component: "article-page";
  _uid: string;
  [k: string]: unknown;
}

export interface Banner {
  background_image?: StoryblokAsset;
  background_image_cover?: boolean;
  background_image_alignment?: "left" | "center" | "right";
  background_image_width?: "100" | "75" | "50";
  background_video?: StoryblokAsset;
  background_color?: number | string;
  headline?: HeadlineSegment[];
  lead?: string;
  buttons?: Button[];
  text_alignment?: "center" | "left";
  component: "banner";
  _uid: string;
  [k: string]: unknown;
}

export interface BannerReference {
  banners?: (ISbStoryData<Banner> | string)[];
  component: "banner-reference";
  _uid: string;
  [k: string]: unknown;
}

export interface Button {
  style?: "default" | "ghost";
  background_color?: number | string;
  text_color?: "white" | "primary-dark";
  size?: "small" | "medium" | "large";
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface Category {
  headline?: string;
  icon?: StoryblokAsset;
  meta_title?: string;
  meta_description?: string;
  component: "category";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactFormSection {
  headline?: HeadlineSegment[];
  text?: StoryblokRichtext;
  button?: Button[];
  image?: StoryblokAsset;
  quote?: string;
  name?: string;
  position?: string;
  component: "contact-form-section";
  _uid: string;
  [k: string]: unknown;
}

export interface DefaultPage {
  meta_title?: string;
  meta_description?: string;
  body?: (
    | Banner
    | BannerReference
    | FaqSection
    | FeaturedArticlesSection
    | FormSection
    | GridSection
    | HeroSection
    | ImageTextSection
    | LatestArticlesSection
    | LogoSection
    | PersonalizedSection
    | ProductsSection
    | TabbedContentSection
    | TestimonialsSection
    | TextSection
    | TwoColumnsSection
  )[];
  component: "default-page";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqEntry {
  question?: string;
  answer?: StoryblokRichtext;
  component: "faq-entry";
  _uid: string;
  [k: string]: unknown;
}

export interface FaqSection {
  headline?: HeadlineSegment[];
  lead?: string;
  faq_entries?: FaqEntry[];
  component: "faq-section";
  _uid: string;
  [k: string]: unknown;
}

export interface FeaturedArticlesSection {
  headline?: HeadlineSegment[];
  lead?: string;
  articles?: (ISbStoryData<ArticlePage> | string)[];
  cols?: "2" | "3" | "4";
  background_color?: number | string;
  component: "featured-articles-section";
  _uid: string;
  [k: string]: unknown;
}

export interface FormSection {
  headline?: HeadlineSegment[];
  form?: "contact" | "newsletter";
  button?: Button[];
  component: "form-section";
  _uid: string;
  [k: string]: unknown;
}

export interface GridCard {
  bold_text?: string;
  label?: string;
  text?: string;
  button?: Button[];
  row_span?: "1" | "2";
  border?: boolean;
  background_image?: StoryblokAsset;
  icon_width?: "48" | "80" | "160" | "200";
  icon?: StoryblokAsset;
  component: "grid-card";
  _uid: string;
  [k: string]: unknown;
}

export interface GridSection {
  cards?: (GridCard | PriceCard | ImageCard)[];
  cols?: "2" | "3" | "4";
  headline?: HeadlineSegment[];
  lead?: string;
  background_color?: number | string;
  button?: Button[];
  component: "grid-section";
  _uid: string;
  [k: string]: unknown;
}

export interface HeadlineSegment {
  text?: string;
  highlight?: "none" | "color_1" | "color_2" | "color_3";
  component: "headline-segment";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroSection {
  layout?: "stacked" | "split";
  background_color?: number | string;
  secondary_background_color?:
    | ""
    | "medium"
    | '["#E4DDB9", "#A59441", "#9D86F7", "#8D60FF", "#F5F5F7", "#FFFFFF"]'
    | "#A59441";
  text_alignment?: "left" | "center";
  image_decoration?: boolean;
  eyebrow?: string;
  headline?: HeadlineSegment[];
  text?: string;
  buttons?: Button[];
  image?: StoryblokAsset;
  preserve_image_aspect_ratio?: boolean;
  component: "hero-section";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageCard {
  image?: StoryblokAsset;
  label?: string;
  text?: string;
  background_color?: "" | "medium" | "#fbe8d5" | '["#d8d4f9", "#fbe8d5", "#e9e8d2", "#e3f0d5", "#f8d7d4", "#d9e4f1"]';
  component: "image-card";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageTextSection {
  background_color?: number | string;
  reverse_mobile_layout?: boolean;
  reverse_desktop_layout?: boolean;
  eyebrow?: string;
  headline?: HeadlineSegment[];
  text?: StoryblokRichtext;
  buttons?: Button[];
  image?: StoryblokAsset;
  preserve_image_aspect_ratio?: boolean;
  component: "image-text-section";
  _uid: string;
  [k: string]: unknown;
}

export interface LatestArticlesSection {
  headline?: HeadlineSegment[];
  lead?: string;
  component: "latest-articles-section";
  _uid: string;
  [k: string]: unknown;
}

export interface LogoSection {
  lead?: string;
  logos?: StoryblokMultiasset;
  component: "logo-section";
  _uid: string;
  [k: string]: unknown;
}

export interface NavItem {
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "nav-item";
  _uid: string;
  [k: string]: unknown;
}

export interface NewsletterFormSection {
  headline?: HeadlineSegment[];
  button?: Button[];
  component: "newsletter-form-section";
  _uid: string;
  [k: string]: unknown;
}

export interface PersonalizedSection {
  preview?: "new_visitor" | "returning_visitor";
  returning_visitor?: unknown;
  returning_visitor_blocks?: (
    | Banner
    | BannerReference
    | FaqSection
    | FeaturedArticlesSection
    | FormSection
    | GridSection
    | HeroSection
    | ImageTextSection
    | LatestArticlesSection
    | LogoSection
    | PersonalizedSection
    | ProductsSection
    | TabbedContentSection
    | TestimonialsSection
    | TextSection
    | TwoColumnsSection
  )[];
  new_visitor?: unknown;
  new_visitor_blocks?: (
    | Banner
    | BannerReference
    | FaqSection
    | FeaturedArticlesSection
    | FormSection
    | GridSection
    | HeroSection
    | ImageTextSection
    | LatestArticlesSection
    | LogoSection
    | PersonalizedSection
    | ProductsSection
    | TabbedContentSection
    | TestimonialsSection
    | TextSection
    | TwoColumnsSection
  )[];
  component: "personalized-section";
  _uid: string;
  [k: string]: unknown;
}

export interface PriceCard {
  most_popular?: boolean;
  headline?: string;
  text_1?: StoryblokRichtext;
  price?: string;
  button?: Button[];
  text_2?: StoryblokRichtext;
  component: "price-card";
  _uid: string;
  [k: string]: unknown;
}

export interface ProductsSection {
  headline?: HeadlineSegment[];
  lead?: string;
  plugin?: unknown;
  component: "products-section";
  _uid: string;
  [k: string]: unknown;
}

export interface RichtextYoutube {
  video_id?: string;
  component: "richtext-youtube";
  _uid: string;
  [k: string]: unknown;
}

export interface SiteConfig {
  primary_highlight_color?: unknown;
  highlight_1_color?: unknown;
  highlight_2_color?: unknown;
  highlight_3_color?: unknown;
  primary_background_color?: unknown;
  background_1_color?: unknown;
  background_2_color?: unknown;
  background_3_color?: unknown;
  background_4_color?: unknown;
  background_5_color?: unknown;
  background_6_color?: unknown;
  background_7_color?: unknown;
  background_8_color?: unknown;
  background_9_color?: unknown;
  background_10_color?: unknown;
  primary_dark_color?: unknown;
  header_light?: boolean;
  disable_rounded_corners?: boolean;
  footer_light?: boolean;
  footer_decoration?: boolean;
  use_custom_colors?: boolean;
  colors?: unknown;
  colored_headlines?: boolean;
  use_custom_fonts?: boolean;
  custom_font_display?: number | string;
  custom_font_body?: number | string;
  x?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  footer_headline?: HeadlineSegment[];
  footer_about?: StoryblokRichtext;
  footer_nav_1_headline?: string;
  footer_nav_1?: NavItem[];
  footer_nav_2_headline?: string;
  footer_nav_2?: NavItem[];
  footer_nav_3_headline?: string;
  footer_nav_3?: NavItem[];
  header_logo?: StoryblokAsset;
  header_nav?: NavItem[];
  header_buttons?: Button[];
  instagram?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  youtube?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  facebook?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "site-config";
  _uid: string;
  [k: string]: unknown;
}

export interface TabbedContentEntry {
  image?: StoryblokAsset;
  headline?: string;
  description?: StoryblokRichtext;
  button?: Button[];
  component: "tabbed-content-entry";
  _uid: string;
  [k: string]: unknown;
}

export interface TabbedContentSection {
  headline?: HeadlineSegment[];
  lead?: string;
  entries?: TabbedContentEntry[];
  component: "tabbed-content-section";
  _uid: string;
  [k: string]: unknown;
}

export interface Testimonial {
  quote?: string;
  photo?: StoryblokAsset;
  name?: string;
  role?: string;
  component: "testimonial";
  _uid: string;
  [k: string]: unknown;
}

export interface TestimonialsSection {
  headline?: HeadlineSegment[];
  lead?: string;
  testimonials?: (ISbStoryData<Testimonial> | ISbStoryData<Testimonial> | string)[];
  component: "testimonials-section";
  _uid: string;
  [k: string]: unknown;
}

export interface TextSection {
  eyebrow?: string;
  text_alignment?: "left" | "center";
  headline?: HeadlineSegment[];
  text?: StoryblokRichtext;
  buttons?: Button[];
  background_color?: number | string;
  component: "text-section";
  _uid: string;
  [k: string]: unknown;
}

export interface TwoColumnsSection {
  column_1_headline?: HeadlineSegment[];
  column_1_text_1?: StoryblokRichtext;
  column_1_text_2?: StoryblokRichtext;
  column_1_button?: Button[];
  column_1_image?: StoryblokAsset;
  column_1_background_color?: "" | "medium" | "#BCE2FF" | '["#f4f2ea", "#d8d4f9", "#BCE2FF"]';
  column_2_headline?: HeadlineSegment[];
  column_2_text_1?: StoryblokRichtext;
  column_2_button?: Button[];
  column_2_background_color?: "" | "medium" | "#d8d4f9" | '["#f4f2ea", "#d8d4f9", "#BCE2FF"]';
  column_1_decoration_color?: "" | "medium" | "#71b3f9" | '["#dfdbbb", "#9987f0", "#71b3f9"]';
  column_2_decoration_color?: "" | "medium" | "#9987f0" | '["#dfdbbb", "#9987f0", "#71b3f9"]';
  component: "two-columns-section";
  _uid: string;
  [k: string]: unknown;
}
