openapi: 3.1.1
info:
  title: Storyblok Content Delivery API - Data Sources
  version: 1.0.0
  description: |
    Content Delivery API for retrieving Storyblok datasources.
    
    This endpoint provides access to all datasources in the space.
servers:
  $ref: ../shared/servers.yaml
security:
  $ref: ../shared/security.yaml
paths:
  /cdn/datasources:
    get:
      operationId: getDatasources
      summary: Retrieve Multiple Datasources
      description: |
        Returns an array of all datasources (as datasource objects) contained in a Storyblok space.
        
        This endpoint is paginated by default, including a maximum of 1000 datasources in the response.
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 25
          description: Number of datasources per page (max 1000)
      responses:
        '200':
          $ref: ../shared/responses.yaml#/DatasourcesResponse
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: ../shared/responses.yaml#/ErrorResponse
        '429':
          description: Too Many Requests - Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: ../shared/responses.yaml#/ErrorResponse

  /cdn/datasources/{id}:
    get:
      operationId: getDatasource
      summary: Retrieve a Single Datasource
      description: |
        Returns a single datasource object for the specified ID.
        
        This endpoint returns detailed information about a specific datasource including its dimensions.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The numeric ID of the datasource
      responses:
        '200':
          $ref: ../shared/responses.yaml#/DatasourceResponse
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: ../shared/responses.yaml#/ErrorResponse
        '404':
          description: Not Found - Datasource not found
          content:
            application/json:
              schema:
                $ref: ../shared/responses.yaml#/ErrorResponse
        '429':
          description: Too Many Requests - Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: ../shared/responses.yaml#/ErrorResponse

components: 
  securitySchemes:
    $ref: ../shared/security-schemes.yaml#/securitySchemes
