openapi: 3.1.1
info:
  title: Storyblok Datasources API
  version: 1.0.0
  description: API for delivering Storyblok datasources
servers:
  $ref: ../shared/servers.yaml
security:
  $ref: ../shared/security.yaml
paths:
  /v2/cdn/datasources:
    get:
      operationId: getAll
      summary: Retrieve Multiple Datasources
      description: Returns an array of all datasources with pagination support.
      parameters:
        - name: page
          in: query
          required: false
          description: Page number for pagination
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          required: false
          description: Number of datasources per page (default 25, max 1000)
          schema:
            type: integer
            default: 25
            maximum: 1000
      responses:
        '200':
          description: Array of datasources
          headers:
            $ref: ../../shared/pagination.yaml#/pagination_headers
          content:
            application/json:
              schema:
                type: object
                required:
                  - datasources
                properties:
                  datasources:
                    type: array
                    description: Array of datasource objects
                    items:
                      $ref: '#/components/schemas/Datasource'
                  cv:
                    type: integer
                    description: Cache version Unix timestamp
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /v2/cdn/datasources/{id}:
    get:
      operationId: get
      summary: Retrieve One Datasource
      description: Returns a single datasource object for the specified ID
      parameters:
        - name: id
          in: path
          required: true
          description: Datasource identifier (numeric ID)
          schema:
            type: integer
          examples:
            id:
              summary: By numeric ID
              value: 12345
      responses:
        '200':
          description: Datasource details
          content:
            application/json:
              schema:
                type: object
                required:
                  - datasource
                properties:
                  datasource:
                    $ref: '#/components/schemas/Datasource'
                  cv:
                    type: integer
                    description: Cache version Unix timestamp
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Datasource not found
components:
  securitySchemes:
    $ref: ../shared/security-schemes.yaml#/securitySchemes
  schemas:
    Datasource:
      $ref: ../shared/datasources/datasource-capi.yaml
