/**
 * AST post-processor that takes hey-api's intermediate `types.gen.ts` for a
 * single spec source and emits a clean, sliced, aliased file. Applies:
 *
 *   - slice: keep only declarations transitively reachable from the requested
 *     upstream-name roots,
 *   - rename: rewrite `export type <source>` → `export type <emitAs>` and all
 *     refs to that name accordingly,
 *   - unwrap: when an alias declares `unwrap: 'story'`, lift the type of that
 *     property out of the envelope and use it as the body of the new
 *     declaration.
 *
 * Upstream names never appear in the final output. The hey-api intermediate
 * lives in a tool-owned temp dir and is not committed.
 */

import ts from 'typescript';

export interface KeepEntry {
  /** Upstream schema name as it appears in hey-api's output. */
  source: string;
  /** Final public name to emit. */
  emitAs: string;
  /** Property to lift out of a request envelope. */
  unwrap?: string;
}

export interface TransformResult {
  /** Final file content. */
  output: string;
  /** Names actually emitted (after slicing + transitive walk). */
  emitted: readonly string[];
}

const FILE_HEADER = '// Generated by @storyblok/openapi-codegen. Do not edit by hand.\n\n';

export function transformGeneratedFile(
  sourceText: string,
  keep: readonly KeepEntry[],
  /** Map of upstream-name → emitAs for ALL aliases, used to rewrite refs inside kept bodies. */
  renameMap: ReadonlyMap<string, string>,
): TransformResult {
  const src = ts.createSourceFile('input.ts', sourceText, ts.ScriptTarget.Latest, true);

  // Index every type-alias / interface declaration by upstream name.
  const declMap = new Map<string, ts.TypeAliasDeclaration | ts.InterfaceDeclaration>();
  for (const stmt of src.statements) {
    if (ts.isTypeAliasDeclaration(stmt) || ts.isInterfaceDeclaration(stmt)) {
      declMap.set(stmt.name.text, stmt);
    }
  }

  // BFS over the type-ref graph starting from the requested upstream roots.
  const transitive = new Set<string>();
  const queue: string[] = [];
  for (const entry of keep) {
    if (!declMap.has(entry.source)) {
      throw new Error(`Upstream type "${entry.source}" not found in generated output.`);
    }
    queue.push(entry.source);
  }
  while (queue.length > 0) {
    const name = queue.shift()!;
    if (transitive.has(name)) {
      continue;
    }
    transitive.add(name);
    const decl = declMap.get(name);
    if (!decl) {
      continue;
    }
    collectTypeRefs(decl, (ref) => {
      if (declMap.has(ref) && !transitive.has(ref)) {
        queue.push(ref);
      }
    });
  }

  // Group `keep` entries by upstream source so a single source can emit under
  // multiple aliases (e.g. InternalTagRequest → InternalTagCreate + InternalTagUpdate).
  const keepBySource = new Map<string, KeepEntry[]>();
  for (const entry of keep) {
    const arr = keepBySource.get(entry.source) ?? [];
    arr.push(entry);
    keepBySource.set(entry.source, arr);
  }

  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const emitted: string[] = [];
  const chunks: string[] = [];

  for (const upstreamName of transitive) {
    const decl = declMap.get(upstreamName)!;
    const entries = keepBySource.get(upstreamName) ?? [];
    const primary = entries[0];
    const primaryEmit = primary?.emitAs ?? renameMap.get(upstreamName) ?? upstreamName;
    const unwrap = primary?.unwrap;

    const typeNode = declToTypeNode(decl);
    let body: ts.TypeNode = typeNode;
    if (unwrap) {
      // Dotted paths (e.g. `body.asset_folder`) traverse nested property types.
      for (const segment of unwrap.split('.')) {
        const extracted = extractProperty(body, segment);
        if (!extracted) {
          throw new Error(`Cannot unwrap '${segment}' from "${upstreamName}" (full path: ${unwrap}).`);
        }
        body = extracted;
      }
    }

    body = rewriteRefs(body, renameMap);

    const newDecl = withLeadingComments(
      sourceText,
      decl,
      ts.factory.createTypeAliasDeclaration(
        [ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)],
        ts.factory.createIdentifier(primaryEmit),
        undefined,
        body,
      ),
    );

    chunks.push(printer.printNode(ts.EmitHint.Unspecified, newDecl, src));
    emitted.push(primaryEmit);

    // Secondary aliases for the same upstream source emit as `type X = Primary`.
    for (let i = 1; i < entries.length; i++) {
      const secondary = entries[i];
      chunks.push(`export type ${secondary.emitAs} = ${primaryEmit};`);
      emitted.push(secondary.emitAs);
    }
  }

  return {
    output: `${FILE_HEADER + chunks.join('\n\n')}\n`,
    emitted,
  };
}

function declToTypeNode(decl: ts.TypeAliasDeclaration | ts.InterfaceDeclaration): ts.TypeNode {
  if (ts.isTypeAliasDeclaration(decl)) {
    return decl.type;
  }
  // Interface → TypeLiteral (members), plus extends → intersection if needed.
  const literal = ts.factory.createTypeLiteralNode(decl.members);
  const heritage = decl.heritageClauses?.[0]?.types;
  if (heritage && heritage.length > 0) {
    const parts = heritage.map(h => ts.factory.createTypeReferenceNode(h.expression as ts.Identifier, h.typeArguments));
    return ts.factory.createIntersectionTypeNode([...parts, literal]);
  }
  return literal;
}

function withLeadingComments<T extends ts.Node>(sourceText: string, from: ts.Node, to: T): T {
  let node = to;
  const comments = ts.getLeadingCommentRanges(sourceText, from.getFullStart()) ?? [];
  for (const comment of comments) {
    const isBlock = comment.kind === ts.SyntaxKind.MultiLineCommentTrivia;
    const start = comment.pos + 2;
    const end = isBlock ? comment.end - 2 : comment.end;
    node = ts.addSyntheticLeadingComment(
      node,
      comment.kind,
      sourceText.slice(start, end),
      true,
    ) as T;
  }
  return node;
}

function collectTypeRefs(node: ts.Node, visit: (name: string) => void): void {
  function walk(n: ts.Node): void {
    if (ts.isTypeReferenceNode(n) && ts.isIdentifier(n.typeName)) {
      visit(n.typeName.text);
    }
    // Heritage (`extends Base`) is an ExpressionWithTypeArguments, not a
    // TypeReferenceNode, so the base name would otherwise dangle when only the
    // derived type is kept. declToTypeNode lifts these into an intersection.
    else if (ts.isExpressionWithTypeArguments(n) && ts.isIdentifier(n.expression)) {
      visit(n.expression.text);
    }
    ts.forEachChild(n, walk);
  }
  ts.forEachChild(node, walk);
}

function extractProperty(typeNode: ts.TypeNode, propName: string): ts.TypeNode | undefined {
  if (ts.isTypeLiteralNode(typeNode)) {
    for (const member of typeNode.members) {
      if (
        ts.isPropertySignature(member)
        && member.name
        && ts.isIdentifier(member.name)
        && member.name.text === propName
        && member.type
      ) {
        return member.type;
      }
    }
  }
  if (ts.isIntersectionTypeNode(typeNode)) {
    for (const t of typeNode.types) {
      const found = extractProperty(t, propName);
      if (found) {
        return found;
      }
    }
  }
  return undefined;
}

function rewriteRefs(node: ts.TypeNode, renameMap: ReadonlyMap<string, string>): ts.TypeNode {
  const result = ts.transform(node, [(ctx) => {
    const visit: ts.Visitor = (n) => {
      if (ts.isTypeReferenceNode(n) && ts.isIdentifier(n.typeName)) {
        const original = n.typeName.text;
        const mapped = renameMap.get(original);
        if (mapped && mapped !== original) {
          return ctx.factory.updateTypeReferenceNode(
            n,
            ctx.factory.createIdentifier(mapped),
            n.typeArguments ? ts.visitNodes(n.typeArguments, visit) as ts.NodeArray<ts.TypeNode> : undefined,
          );
        }
      }
      return ts.visitEachChild(n, visit, ctx);
    };
    return n => ts.visitNode(n, visit) as ts.TypeNode;
  }]);
  const transformed = result.transformed[0] as ts.TypeNode;
  result.dispose();
  return transformed;
}
