name: 🐛 Bug Report
description: Report a bug in any of the Storyblok SDK packages
title: "🐛 [Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        **🚨 Issues are primarily for bug reports.** For questions, feature requests, and general discussions, please use [GitHub Discussions](https://github.com/storyblok/monoblok/discussions) instead.
        
        Please provide as much detail as possible to help us investigate and fix the issue.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which Storyblok package is this bug related to?
      options:
        - "@storyblok/js (Core JavaScript SDK)"
        - "@storyblok/js-client (Client SDK)" 
        - "@storyblok/richtext (Rich Text Renderer)"
        - "@storyblok/react (React Integration)"
        - "@storyblok/vue (Vue Integration)"
        - "@storyblok/nuxt (Nuxt Module)"
        - "@storyblok/svelte (Svelte Integration)"
        - "@storyblok/astro (Astro Integration)"
        - "Multiple packages"
        - "Other/Unknown"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: "e.g., 5.0.0"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize Storyblok with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample that reproduces the issue
      render: javascript
      placeholder: |
        // Your code here
        import { storyblokInit } from '@storyblok/js'
        
        // ...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g., macOS 13.0, Windows 11, Ubuntu 22.04]
        - Browser: [e.g., Chrome 118, Firefox 119, Safari 16]
        - Node.js version: [e.g., 18.17.0]
        - Framework version: [e.g., React 18.2.0, Vue 3.3.0, Nuxt 3.8.0]
        - Build tool: [e.g., Vite 4.5.0, Webpack 5.88.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add any error messages or logs
      render: shell
      placeholder: Paste any error messages here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information that might help...

 
