openapi: 3.1.1
info:
  title: Storyblok Internal Tags API
  version: 1.0.0
  description: API for managing Storyblok internal tags
servers:
  $ref: ../../shared/servers.yaml
security:
  $ref: ../../shared/security.yaml
paths:
  /v1/spaces/{space_id}/internal_tags:
    get:
      operationId: getInternalTags
      summary: Retrieve Multiple Internal Tags
      parameters:
        - name: space_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the Storyblok space.
      responses:
        '200':
          description: List of internal tags
          content:
            application/json:
              schema:
                type: object
                properties:
                  internal_tags:
                    type: array
                    items:
                      $ref: '#/components/schemas/InternalTag'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Space not found
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Bearer token authentication
  schemas:
    InternalTag:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
