import { relative } from "pathe";

import { toPascalCase } from "../../../../utils/format";
import {
  componentFileName,
  resolveFileNames,
  resolveVarNames,
  toSafeIdentifier,
} from "../../../schema/utils";
import { toDeclarationFileName, toDeclarationImportSpecifier } from "../filename";
import type { FieldPluginsSource } from "./field-plugins";
import type { SerializedBlock } from "./serialize";

/** Prefix/suffix applied to every emitted type name. */
export interface NameOptions {
  typePrefix?: string;
  typeSuffix?: string;
}

/**
 * Every name the generated file declares. Resolved once so declarations and
 * internal references can never drift apart under `--type-prefix`/`--type-suffix`.
 */
export interface EmittedNames {
  blocks: string;
  schema: string;
  fieldPlugins: string;
  block: string;
  anyBlock: string;
  story: string;
  storyMapi: string;
  /** Technical component name → its definition type name. */
  definitionByComponent: Map<string, string>;
}

export interface RenderOptions extends NameOptions {
  blocks: SerializedBlock[];
  fieldPlugins: FieldPluginsSource;
  /** Posix specifier from the output file to the field-plugins module. */
  fieldPluginsImportPath?: string;
  space: string;
}

function decorate(base: string, options: NameOptions): string {
  return `${options.typePrefix ?? ""}${base}${options.typeSuffix ?? ""}`;
}

/**
 * Resolves the emitted names for a set of components. Definition names are
 * `<Pascal>BlockDefinition`; components whose names collapse to the same
 * PascalCase identifier (e.g. `teaser-list` and `teaser_list`) get a numeric
 * suffix via {@link resolveVarNames} so the file never declares a duplicate.
 *
 * `toSafeIdentifier` runs on the finished base name, because Storyblok accepts
 * component names starting with a digit (`2_col`) and an unguarded `2Col…` would
 * make the entire emitted file unparseable, not just its own declaration.
 */
export function buildNames(componentNames: string[], options: NameOptions): EmittedNames {
  const bases = resolveVarNames(componentNames, (name) =>
    toSafeIdentifier(`${toPascalCase(name)}BlockDefinition`),
  );
  return {
    blocks: decorate("Blocks", options),
    schema: decorate("Schema", options),
    fieldPlugins: decorate("FieldPlugins", options),
    block: decorate("Block", options),
    anyBlock: decorate("AnyBlock", options),
    story: decorate("Story", options),
    storyMapi: decorate("StoryMapi", options),
    // Assumes component names are unique, which MAPI enforces per space, so two
    // components can never collapse into the same map entry here.
    definitionByComponent: new Map(
      componentNames.map((name, i) => [name, decorate(bases[i], options)]),
    ),
  };
}

/**
 * TypeScript source extensions mapped to the module extension an importer must
 * write. TypeScript resolves `./x.js` to `x.ts`, so the emitted specifier names
 * the *output* file even though the module on disk is TypeScript.
 */
const IMPORT_EXTENSION_BY_SOURCE_EXTENSION: ReadonlyArray<readonly [RegExp, string]> = [
  [/\.tsx?$/, ".js"],
  [/\.mts$/, ".mjs"],
  [/\.cts$/, ".cjs"],
];

/**
 * Builds a posix relative import specifier.
 *
 * The extension is rewritten rather than stripped: an extension-less relative
 * specifier is an error under `moduleResolution: node16`/`nodenext` in an ESM
 * package (TS2835), and this file is generated code the user is told not to
 * edit, so they have no way to repair it. A `.js`-style specifier resolves under
 * every mode, including `bundler` and legacy `node10`, so this is strictly wider
 * than the extension-less form. A module that already has a JavaScript
 * extension keeps it.
 */
export function toRelativeImport(fromDir: string, toFile: string): string {
  const path = relative(fromDir, toFile);
  const mapping = IMPORT_EXTENSION_BY_SOURCE_EXTENSION.find(([pattern]) => pattern.test(path));
  const specifier = mapping === undefined ? path : path.replace(mapping[0], mapping[1]);
  return specifier.startsWith(".") ? specifier : `./${specifier}`;
}

/** The file header, identical across single-file and separate-file output. */
export function renderHeader(space: string): string[] {
  return [
    "// This file was generated by the Storyblok CLI. Do not edit by hand.",
    `// Space: ${space}`,
    "",
  ];
}

/**
 * Whether the emitted file derives `FieldPlugins` from a user module, as opposed
 * to declaring it empty.
 *
 * Both the `@storyblok/schema` import line and the `FieldPlugins` declaration
 * must agree on this: `InferSchema` is used by exactly the branches that import
 * the user module, so deciding it once is what keeps the file from importing a
 * name it never references.
 */
function usesUserFieldPlugins(
  options: Pick<RenderOptions, "fieldPlugins" | "fieldPluginsImportPath">,
): boolean {
  return options.fieldPlugins.kind !== "none" && options.fieldPluginsImportPath !== undefined;
}

/**
 * The `@storyblok/schema` import line. `InferStory`/`InferStoryMapi` back the
 * always-emitted `Story`/`StoryMapi` aliases; `InferSchema` is only consumed
 * when {@link renderFieldPlugins} imports a user module. Names stay
 * alphabetically ordered either way.
 */
function renderSchemaImport(
  options: Pick<RenderOptions, "fieldPlugins" | "fieldPluginsImportPath">,
): string {
  const names = ["BlockContent", "MapiStory as InferStoryMapi"];
  if (usesUserFieldPlugins(options)) {
    names.push("Schema as InferSchema");
  }
  names.push("Story as InferStory");
  return `import type { ${names.join(", ")} } from '@storyblok/schema';`;
}

/**
 * Renders the `FieldPlugins` declaration plus the import it needs.
 *
 * Both accepted module shapes resolve through `@storyblok/schema`'s `Schema`
 * helper, so the `fieldType → value` mapping is derived by the library rather
 * than reconstructed here. A bare `fieldPlugins` record is wrapped in a
 * synthetic schema whose `blocks` is `Record<string, never>`, `never` satisfies
 * the `Record<string, Block>` constraint, and the wrapper's `blocks` is never read.
 */
function renderFieldPlugins(
  options: RenderOptions,
  names: EmittedNames,
): { imports: string[]; declaration: string } {
  const { fieldPlugins, fieldPluginsImportPath } = options;

  if (!usesUserFieldPlugins(options)) {
    return {
      imports: [],
      declaration: `export type ${names.fieldPlugins} = Record<never, never>;`,
    };
  }

  if (fieldPlugins.kind === "schema") {
    return {
      imports: [`import type { schema as userSchema } from '${fieldPluginsImportPath}';`],
      declaration: `export type ${names.fieldPlugins} = InferSchema<typeof userSchema>['fieldPlugins'];`,
    };
  }

  return {
    imports: [`import type { fieldPlugins as userFieldPlugins } from '${fieldPluginsImportPath}';`],
    declaration: `export type ${names.fieldPlugins} = InferSchema<{ blocks: Record<string, never>; fieldPlugins: typeof userFieldPlugins }>['fieldPlugins'];`,
  };
}

/**
 * Renders the shared surface: `Blocks`, `FieldPlugins`, `Schema`, the
 * name-keyed `Block<TName>` helper, `AnyBlock`, and the story aliases.
 *
 * `Block<TName>` is the user-facing type (`Block<'hero'>`); the definition types
 * it indexes into are plumbing for the CAPI/MAPI helpers, `withTypes<Schema>()`,
 * `BlockContent`, `Story`.
 */
function renderSurface(
  names: EmittedNames,
  definitionNames: string[],
  fieldPluginsDeclaration: string,
): string[] {
  return [
    `export type ${names.blocks} = ${definitionNames.join(" | ")};`,
    "",
    fieldPluginsDeclaration,
    "",
    `export type ${names.schema} = { blocks: ${names.blocks}; fieldPlugins: ${names.fieldPlugins} };`,
    "",
    `export type ${names.block}<TName extends ${names.blocks}['name']> = BlockContent<Extract<${names.blocks}, { name: TName }>, ${names.blocks}, ${names.fieldPlugins}>;`,
    "",
    `export type ${names.anyBlock} = BlockContent<${names.blocks}, ${names.blocks}, ${names.fieldPlugins}>;`,
    "",
    `export type ${names.story} = InferStory<${names.blocks}, ${names.fieldPlugins}>;`,
    `export type ${names.storyMapi} = InferStoryMapi<${names.blocks}, ${names.fieldPlugins}>;`,
    "",
  ];
}

/** Renders the whole surface plus every definition type into one file. */
export function renderSchemaTypes(options: RenderOptions): string {
  const componentNames = options.blocks.map((block) => block.componentName);
  const names = buildNames(componentNames, options);
  const fieldPlugins = renderFieldPlugins(options, names);

  const lines = [
    ...renderHeader(options.space),
    renderSchemaImport(options),
    ...fieldPlugins.imports,
    "",
  ];

  for (const block of options.blocks) {
    lines.push(
      `export type ${names.definitionByComponent.get(block.componentName)!} = ${block.definitionBody};`,
    );
    lines.push("");
  }

  const definitionNames = componentNames.map((name) => names.definitionByComponent.get(name)!);
  lines.push(...renderSurface(names, definitionNames, fieldPlugins.declaration));

  return lines.join("\n");
}

/**
 * Renders one file per block definition plus the main file holding the shared
 * surface. Definition literals never reference each other, so the split needs
 * no cross-imports between block files, only the main file imports them.
 *
 * Returns posix relative paths so the caller can join them onto the output
 * directory; keys are stable across platforms.
 */
export function renderSeparateFiles(
  options: RenderOptions & { filename: string },
): Map<string, string> {
  const componentNames = options.blocks.map((block) => block.componentName);
  const names = buildNames(componentNames, options);
  const fieldPlugins = renderFieldPlugins(options, names);
  const fileNames = resolveFileNames(componentNames.map((name) => componentFileName(name)));

  const files = new Map<string, string>();

  options.blocks.forEach((block, index) => {
    const typeName = names.definitionByComponent.get(block.componentName)!;
    files.set(
      `blocks/${fileNames[index]}.d.ts`,
      [
        ...renderHeader(options.space),
        `export type ${typeName} = ${block.definitionBody};`,
        "",
      ].join("\n"),
    );
  });

  const definitionNames = componentNames.map((name) => names.definitionByComponent.get(name)!);
  const mainLines = [
    ...renderHeader(options.space),
    renderSchemaImport(options),
    ...fieldPlugins.imports,
    ...definitionNames.map(
      (typeName, index) =>
        `import type { ${typeName} } from './blocks/${toDeclarationImportSpecifier(fileNames[index])}';`,
    ),
    "",
    ...renderSurface(names, definitionNames, fieldPlugins.declaration),
  ];
  files.set(toDeclarationFileName(options.filename), mainLines.join("\n"));

  return files;
}
