import { relative } from 'pathe';

import { toPascalCase } from '../../../../utils/format';
import { resolveVarNames } from '../../../schema/utils';
import type { FieldPluginsSource } from './field-plugins';
import type { SerializedBlock } from './serialize';

/** Prefix/suffix applied to every emitted type name. */
export interface NameOptions {
  typePrefix?: string;
  typeSuffix?: string;
}

/**
 * Every name the generated file declares. Resolved once so declarations and
 * internal references can never drift apart under `--type-prefix`/`--type-suffix`.
 */
export interface EmittedNames {
  blocks: string;
  schema: string;
  fieldPlugins: string;
  block: string;
  anyBlock: string;
  story: string;
  storyMapi: string;
  /** Technical component name → its definition type name. */
  definitionByComponent: Map<string, string>;
}

export interface RenderOptions extends NameOptions {
  blocks: SerializedBlock[];
  fieldPlugins: FieldPluginsSource;
  /** Posix specifier from the output file to the field-plugins module. */
  fieldPluginsImportPath?: string;
  space: string;
}

function decorate(base: string, options: NameOptions): string {
  return `${options.typePrefix ?? ''}${base}${options.typeSuffix ?? ''}`;
}

/**
 * Resolves the emitted names for a set of components. Definition names are
 * `<Pascal>BlockDefinition`; components whose names collapse to the same
 * PascalCase identifier (e.g. `teaser-list` and `teaser_list`) get a numeric
 * suffix via {@link resolveVarNames} so the file never declares a duplicate.
 */
export function buildNames(componentNames: string[], options: NameOptions): EmittedNames {
  const bases = resolveVarNames(componentNames, name => `${toPascalCase(name)}BlockDefinition`);
  return {
    blocks: decorate('Blocks', options),
    schema: decorate('Schema', options),
    fieldPlugins: decorate('FieldPlugins', options),
    block: decorate('Block', options),
    anyBlock: decorate('AnyBlock', options),
    story: decorate('Story', options),
    storyMapi: decorate('StoryMapi', options),
    definitionByComponent: new Map(componentNames.map((name, i) => [name, decorate(bases[i], options)])),
  };
}

/** Builds a posix, extension-less relative import specifier. */
export function toRelativeImport(fromDir: string, toFile: string): string {
  const specifier = relative(fromDir, toFile).replace(/\.(?:ts|tsx|mts|cts)$/, '');
  return specifier.startsWith('.') ? specifier : `./${specifier}`;
}

/** The file header, identical across single-file and separate-file output. */
export function renderHeader(space: string): string[] {
  return [
    '// This file was generated by the Storyblok CLI. Do not edit by hand.',
    `// Space: ${space}`,
    '',
  ];
}

/**
 * Renders the `FieldPlugins` declaration plus the import it needs.
 *
 * Both accepted module shapes resolve through `@storyblok/schema`'s `Schema`
 * helper, so the `fieldType → value` mapping is derived by the library rather
 * than reconstructed here. A bare `fieldPlugins` record is wrapped in a
 * synthetic schema whose `blocks` is `Record<string, never>`, `never` satisfies
 * the `Record<string, Block>` constraint, and the wrapper's `blocks` is never read.
 */
function renderFieldPlugins(options: RenderOptions, names: EmittedNames): { imports: string[]; declaration: string } {
  const { fieldPlugins, fieldPluginsImportPath } = options;

  if (fieldPlugins.kind === 'none' || fieldPluginsImportPath === undefined) {
    return { imports: [], declaration: `export type ${names.fieldPlugins} = Record<never, never>;` };
  }

  if (fieldPlugins.kind === 'schema') {
    return {
      imports: [`import type { schema as userSchema } from '${fieldPluginsImportPath}';`],
      declaration: `export type ${names.fieldPlugins} = InferSchema<typeof userSchema>['fieldPlugins'];`,
    };
  }

  return {
    imports: [`import type { fieldPlugins as userFieldPlugins } from '${fieldPluginsImportPath}';`],
    declaration: `export type ${names.fieldPlugins} = InferSchema<{ blocks: Record<string, never>; fieldPlugins: typeof userFieldPlugins }>['fieldPlugins'];`,
  };
}

/**
 * Renders the shared surface: `Blocks`, `FieldPlugins`, `Schema`, the
 * name-keyed `Block<TName>` helper, `AnyBlock`, and the story aliases.
 *
 * `Block<TName>` is the user-facing type (`Block<'hero'>`); the definition types
 * it indexes into are plumbing for the CAPI/MAPI helpers, `withTypes<Schema>()`,
 * `BlockContent`, `Story`.
 */
function renderSurface(names: EmittedNames, definitionNames: string[], fieldPluginsDeclaration: string): string[] {
  return [
    `export type ${names.blocks} = ${definitionNames.join(' | ')};`,
    '',
    fieldPluginsDeclaration,
    '',
    `export type ${names.schema} = { blocks: ${names.blocks}; fieldPlugins: ${names.fieldPlugins} };`,
    '',
    `export type ${names.block}<TName extends ${names.blocks}['name']> = BlockContent<Extract<${names.blocks}, { name: TName }>, ${names.blocks}, ${names.fieldPlugins}>;`,
    '',
    `export type ${names.anyBlock} = BlockContent<${names.blocks}, ${names.blocks}, ${names.fieldPlugins}>;`,
    '',
    `export type ${names.story} = InferStory<${names.blocks}>;`,
    `export type ${names.storyMapi} = InferStoryMapi<${names.blocks}>;`,
    '',
  ];
}

/** Renders the whole surface plus every definition type into one file. */
export function renderSchemaTypes(options: RenderOptions): string {
  const componentNames = options.blocks.map(block => block.componentName);
  const names = buildNames(componentNames, options);
  const fieldPlugins = renderFieldPlugins(options, names);

  const lines = [
    ...renderHeader(options.space),
    'import type { BlockContent, MapiStory as InferStoryMapi, Schema as InferSchema, Story as InferStory } from \'@storyblok/schema\';',
    ...fieldPlugins.imports,
    '',
  ];

  for (const block of options.blocks) {
    lines.push(`export type ${names.definitionByComponent.get(block.componentName)!} = ${block.definitionBody};`);
    lines.push('');
  }

  const definitionNames = componentNames.map(name => names.definitionByComponent.get(name)!);
  lines.push(...renderSurface(names, definitionNames, fieldPlugins.declaration));

  return lines.join('\n');
}
