openapi: 3.1.1
info:
  title: Storyblok Datasources API
  version: 1.0.0
  description: API for managing Storyblok datasources
servers:
  $ref: ../shared/servers.yaml
security:
  $ref: ../shared/security.yaml
paths:
  /v1/spaces/{space_id}/datasources:
    get:
      operationId: list
      summary: Retrieve Multiple Datasources
      parameters:
        - $ref: ../shared/parameters.yaml#/space_id
        - name: search
          in: query
          required: false
          schema:
            type: string
          description: Search by name of datasources
        - name: by_ids
          in: query
          required: false
          schema:
            type: string
          description: Search by IDs of datasources (comma separated)
      responses:
        '200':
          description: List of datasources
          content:
            application/json:
              schema:
                type: object
                properties:
                  datasources:
                    type: array
                    items:
                      $ref: '#/components/schemas/Datasource'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Space not found
    post:
      operationId: create
      summary: Create a Datasource
      parameters:
        - $ref: ../shared/parameters.yaml#/space_id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasourceCreateRequest'
      responses:
        '201':
          description: Datasource created
          content:
            application/json:
              schema:
                type: object
                properties:
                  datasource:
                    $ref: '#/components/schemas/Datasource'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Space not found
  /v1/spaces/{space_id}/datasources/{datasource_id}:
    get:
      operationId: get
      summary: Retrieve One Datasource
      parameters:
        - $ref: ../shared/parameters.yaml#/space_id
        - name: datasource_id
          in: path
          required: true
          schema:
            type: integer
          description: Numeric id of a datasource
      responses:
        '200':
          description: Datasource details
          content:
            application/json:
              schema:
                type: object
                properties:
                  datasource:
                    $ref: '#/components/schemas/Datasource'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Datasource not found
    put:
      operationId: update
      summary: Update a Datasource
      parameters:
        - $ref: ../shared/parameters.yaml#/space_id
        - name: datasource_id
          in: path
          required: true
          schema:
            type: integer
          description: Numeric id of a datasource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasourceUpdateRequest'
      responses:
        '200':
          description: Datasource updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  datasource:
                    $ref: '#/components/schemas/Datasource'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Datasource not found
    delete:
      operationId: delete
      summary: Delete a Datasource
      parameters:
        - $ref: ../shared/parameters.yaml#/space_id
        - name: datasource_id
          in: path
          required: true
          schema:
            type: integer
          description: Numeric id of a datasource
      responses:
        '204':
          description: Datasource deleted
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Datasource not found
components:
  securitySchemes:
    $ref: ../shared/security-schemes.yaml#/securitySchemes
  schemas:
    Datasource:
      type: object
      properties:
        id:
          type: integer
          description: The numeric ID of the datasource
        name:
          type: string
          description: The complete name provided for a datasource
        slug:
          type: string
          description: Slug of a datasource
        dimensions:
          type: array
          description: An array listing the dimensions (e.g., per country, region, language, or other context) defined for the datasource
          items:
            type: object
            properties:
              id:
                type: integer
                description: The numeric ID
              name:
                type: string
                description: The complete name provided for the datasource
              entry_value:
                type: string
                description: The value provided for the datasource dimension (e.g., a language code)
              datasource_id:
                type: integer
                description: The numeric ID of the datasource that the dimension belongs to
              created_at:
                type: string
                format: date-time
                description: Creation date
              updated_at:
                type: string
                format: date-time
                description: Latest update date
        created_at:
          type: string
          format: date-time
          description: Creation date
        updated_at:
          type: string
          format: date-time
          description: Latest update date
    DatasourceCreateRequest:
      type: object
      properties:
        datasource:
          type: object
          required:
            - name
            - slug
          properties:
            name:
              type: string
              description: The complete name provided for a datasource
            slug:
              type: string
              description: Slug of a datasource
            dimensions_attributes:
              type: array
              description: An array of dimension attributes for creating dimensions within the datasource
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: The complete name provided for the datasource dimension
                  entry_value:
                    type: string
                    description: The value provided for the datasource dimension (e.g., a language code)
                    
    DatasourceUpdateRequest:
      type: object
      properties:
        datasource:
          type: object
          properties:
            name:
              type: string
              description: The complete name provided for a datasource
            slug:
              type: string
              description: Slug of a datasource
            dimensions_attributes:
              type: array
              description: An array of dimension attributes for updating dimensions within the datasource
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: The complete name provided for the datasource dimension
                  entry_value:
                    type: string
                    description: The value provided for the datasource dimension (e.g., a language code)
