/**
 * Regenerates `src/known-types.ts` after a successful spec fetch.
 *
 * The emitted file keeps the public `KnownType` type unchanged (still derived
 * from `ALIASES` + `TEMPLATES` at the type level), and adds an informational
 * `UPSTREAM_SCHEMAS` const enumerating every schema discovered in the cached
 * specs. Contributors can scan this to find candidates for new aliases without
 * grepping the YAMLs.
 *
 * Validation runs before writing: every `ALIASES[].source` must exist as a
 * schema in its declared `spec`, and every `TEMPLATES[*].sourceLeaves` entry
 * must match an `ALIASES[].emitAs`. Mismatches throw — the generator fails
 * loud rather than emitting a stale catalog.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'pathe';
import { ALIASES, type SpecSource } from '../src/aliases.ts';
import { TEMPLATES } from '../src/templates.ts';
import { CACHE_DIR, TOOL_ROOT } from './lock.ts';

const KNOWN_TYPES_PATH = resolve(TOOL_ROOT, 'src/known-types.ts');
const OVERLAY_PATH = resolve(TOOL_ROOT, 'specs/overlay.openapi.yaml');
const SPEC_PATHS: Record<SpecSource, string> = {
  capi: resolve(CACHE_DIR, 'capi/cdn-v2.openapi.yaml'),
  mapi: resolve(CACHE_DIR, 'mapi/management-v1.openapi.yaml'),
  overlay: OVERLAY_PATH,
};

/**
 * Extracts top-level schema names from `components.schemas` in an OpenAPI
 * YAML. Relies on the upstream specs using 2-space indentation.
 */
export function listSchemaNames(yamlPath: string): string[] {
  const lines = readFileSync(yamlPath, 'utf8').split('\n');
  const schemasIndex = lines.findIndex(line => /^ {2}schemas:\s*$/.test(line));
  if (schemasIndex === -1) {
    throw new Error(`Could not locate \`  schemas:\` block in ${yamlPath}`);
  }

  const names: string[] = [];
  for (let i = schemasIndex + 1; i < lines.length; i++) {
    const line = lines[i];
    if (line === '' || /^\s*#/.test(line)) {
      continue;
    }
    // Any top-level key or next `components` sibling ends `schemas`.
    if (/^\S/.test(line) || /^ {2}\S/.test(line)) {
      break;
    }
    const match = /^ {4}([A-Z_]\w*):\s*$/i.exec(line);
    if (match) {
      names.push(match[1]);
    }
  }

  return names.sort();
}

function toPascalCase(input: string): string {
  return input.charAt(0).toUpperCase() + input.slice(1);
}

/**
 * Operation-derived data types that `@hey-api/openapi-ts` synthesizes for each
 * `operationId` (e.g. `createAssetFolder` → `CreateAssetFolderData`). Aliases
 * may target these in addition to `components.schemas` entries.
 */
export function listOperationDataNames(yamlPath: string): string[] {
  const text = readFileSync(yamlPath, 'utf8');
  const names = new Set<string>();
  for (const match of text.matchAll(/^\s+operationId:\s*([A-Za-z_]\w*)\s*$/gm)) {
    names.add(`${toPascalCase(match[1])}Data`);
  }
  return [...names].sort();
}

function validate(schemasBySpec: Record<SpecSource, ReadonlySet<string>>): void {
  for (const alias of ALIASES) {
    if (!schemasBySpec[alias.spec].has(alias.source)) {
      throw new Error(
        `ALIASES entry { source: '${alias.source}', spec: '${alias.spec}', emitAs: '${alias.emitAs}' } `
        + `does not exist in the ${alias.spec} spec. Either rename the source or remove the alias.`,
      );
    }
  }

  const emitNames = new Set(ALIASES.map(a => a.emitAs));
  for (const [file, meta] of Object.entries(TEMPLATES)) {
    for (const leaf of meta.sourceLeaves) {
      if (!emitNames.has(leaf)) {
        throw new Error(
          `TEMPLATES['${file}'].sourceLeaves entry '${leaf}' has no matching ALIASES[].emitAs.`,
        );
      }
    }
  }
}

function renderArray(names: readonly string[]): string {
  if (names.length === 0) {
    return '[]';
  }
  return `[\n${names.map(n => `    '${n}',`).join('\n')}\n  ]`;
}

function renderFile(schemasBySpec: Record<SpecSource, readonly string[]>): string {
  return `// Generated by \`pnpm --filter @storyblok/openapi-codegen pull\`. Do not edit by hand.
//
// Public catalog of all type names the codegen tool can emit. Drives the
// \`include\` parameter on \`generate()\` and gives IDE autocomplete.
//
// \`UPSTREAM_SCHEMAS\` lists every schema discovered in the cached specs and
// is informational — use it to find candidates for new aliases. The \`KnownType\`
// union remains the source of truth for callable names; extend it by adding to
// \`ALIASES\` (which feeds \`AliasName\`) or to \`TEMPLATES\` (which feeds \`TemplateName\`).

import type { ALIASES } from './aliases.ts';
import type { TEMPLATES } from './templates.ts';

type AliasName = typeof ALIASES[number]['emitAs'];
type TemplateName = typeof TEMPLATES[keyof typeof TEMPLATES]['provides'][number];

export type KnownType = AliasName | TemplateName;

export const UPSTREAM_SCHEMAS = {
  capi: ${renderArray(schemasBySpec.capi)} as const,
  mapi: ${renderArray(schemasBySpec.mapi)} as const,
  overlay: ${renderArray(schemasBySpec.overlay)} as const,
} as const;
`;
}

export function generateKnownTypes(): void {
  const schemasBySpec: Record<SpecSource, readonly string[]> = {
    capi: listSchemaNames(SPEC_PATHS.capi),
    mapi: listSchemaNames(SPEC_PATHS.mapi),
    overlay: listSchemaNames(SPEC_PATHS.overlay),
  };

  const validSourcesBySpec: Record<SpecSource, ReadonlySet<string>> = {
    capi: new Set([...schemasBySpec.capi, ...listOperationDataNames(SPEC_PATHS.capi)]),
    mapi: new Set([...schemasBySpec.mapi, ...listOperationDataNames(SPEC_PATHS.mapi)]),
    overlay: new Set([...schemasBySpec.overlay, ...listOperationDataNames(SPEC_PATHS.overlay)]),
  };

  validate(validSourcesBySpec);

  writeFileSync(KNOWN_TYPES_PATH, renderFile(schemasBySpec), 'utf8');
}

const isDirectInvocation = process.argv[1] === fileURLToPath(import.meta.url);
if (isDirectInvocation) {
  generateKnownTypes();
  console.warn(`Regenerated ${KNOWN_TYPES_PATH}`);
}
