openapi: 3.1.1
info:
  title: Storyblok Internal Tags API
  version: 1.0.0
  description: API for managing Storyblok internal tags
servers:
  $ref: ../shared/servers.yaml
security:
  $ref: ../shared/security.yaml
paths:
  /v1/spaces/{space_id}/internal_tags:
    get:
      operationId: list
      summary: Retrieve Multiple Internal Tags
      parameters:
        - $ref: ../shared/parameters.yaml#/space_id
        - $ref: ../shared/pagination.yaml#/page
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
          description: Number of internal tags per page. Default is 25, maximum is 100.
        - name: search
          in: query
          required: false
          schema:
            type: string
          description: Filter by search term
        - name: by_object_type
          in: query
          required: false
          schema:
            type: string
            enum: [asset, component]
          description: Filter internal tags by object type. Possible values - `asset` or `component`
      responses:
        '200':
          description: List of internal tags
          headers:
            $ref: ../shared/pagination.yaml#/pagination_headers
          content:
            application/json:
              schema:
                type: object
                properties:
                  internal_tags:
                    type: array
                    items:
                      $ref: '#/components/schemas/InternalTag'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Space not found
    post:
      operationId: create
      summary: Create an Internal Tag
      parameters:
        - $ref: ../shared/parameters.yaml#/space_id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalTag'
      responses:
        '201':
          description: Internal tag created
          content:
            application/json:
              schema:
                type: object
                properties:
                  internal_tag:
                    $ref: '#/components/schemas/InternalTag'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Space not found
  /v1/spaces/{space_id}/internal_tags/{internal_tag_id}:
    put:
      operationId: update
      summary: Update an Internal Tag
      parameters:
        - $ref: ../shared/parameters.yaml#/space_id
        - name: internal_tag_id
          in: path
          required: true
          schema:
            type: integer
          description: Numeric ID of the internal tag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalTag'
              required: 
      responses:
        '200':
          description: Internal tag updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  internal_tag:
                    $ref: '#/components/schemas/InternalTag'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Internal tag not found
    delete:
      operationId: delete
      summary: Delete an Internal Tag
      parameters:
        - $ref: ../shared/parameters.yaml#/space_id
        - name: internal_tag_id
          in: path
          required: true
          schema:
            type: integer
          description: Numeric ID of the internal tag
      responses:
        '204':
          description: Internal tag deleted
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Internal tag not found
components:
  securitySchemes:
    $ref: ../shared/security-schemes.yaml#/securitySchemes
  schemas:
    InternalTag:
      type: object
      required: 
        -  id
        - name
        - object_type
      properties:
        name:
          type: string
          description: Name of the internal tag
        id:
          type: integer
          description: Numeric ID of the internal tag
          readOnly: true
        object_type:
          type: string
          enum: [asset, component]
          description: The object type of an internal tag (where does the internal tag belong to). Can be `asset` or `component`
