// Could extend for more attributes if needed
export const hints: Record<string, string> = {
  level: '1 | 2 | 3 | 4 | 5 | 6',
  textAlign: '\'left\' | \'center\' | \'right\' | \'justify\' | null',
  color: 'string | null',
  class: 'string | null',
  id: 'string | null',
  href: 'string',
  linktype: '\'url\' | \'story\' | \'asset\' | \'email\'',
  src: 'string',
  alt: 'string',
  title: 'string | null',
  width: 'number | string | null',
  height: 'number | string | null',
  rel: 'string | null',
  target: '\'_self\' | \'_blank\' | \'_parent\' | \'_top\' | null',
  order: 'number',
  colspan: 'number',
  rowspan: 'number',
  colwidth: 'number[] | null',
  backgroundColor: 'string | null',
  body: 'SbBlokData[]',
  emoji: 'string | null',
  name: 'string | null',
  fallbackImage: 'string | null',
  reporter: 'never',
  // Expand as needed
};
