// generated by discover-schema.ts — DO NOT EDIT
// Reusable field definitions inferred from the WordPress dump.
// Run `pnpm wp:discover` to regenerate.

import { defineField } from '@storyblok/schema';

export const titleField = defineField({ type: 'text' });
export const slugField = defineField({ type: 'text' });
export const datetimeField = defineField({ type: 'datetime' });
export const richtextField = defineField({ type: 'richtext' });
export const bloksField = defineField({ type: 'bloks' });
export const assetField = defineField({ type: 'asset', filetypes: ['images'] });
export const multilinkField = defineField({ type: 'multilink' });
export const numberField = defineField({ type: 'number' });
export const booleanField = defineField({ type: 'boolean' });
