// generated by discover-schema.ts — DO NOT EDIT
// Run `pnpm wp:discover` to regenerate from the WordPress dump.

export const schema = {
  components: {},
  componentFolders: {},
  datasources: {},
};
