// This file was generated by the Storyblok CLI. Do not edit by hand.
// Space: 295018

import type { BlockContent, MapiStory as InferStoryMapi, Schema as InferSchema, Story as InferStory } from '@storyblok/schema';

export type HeroBlockDefinition = {
  readonly id: number;
  created_at: string;
  updated_at: string;
  name: 'hero';
  is_root: false;
  is_nestable: true;
  fields: [
    { name: 'headline'; type: 'text'; required: true },
    { name: 'image'; type: 'asset' },
    { name: 'nested'; type: 'bloks'; allow: ['grid'] },
    { name: 'general'; type: 'tab' },
  ];
};

export type GridBlockDefinition = {
  readonly id: number;
  created_at: string;
  updated_at: string;
  name: 'grid';
  is_root: false;
  is_nestable: true;
  fields: [
    { name: 'columns'; type: 'bloks' },
  ];
};

export type PageBlockDefinition = {
  readonly id: number;
  created_at: string;
  updated_at: string;
  name: 'page';
  is_root: true;
  is_nestable: false;
  fields: [
    { name: 'body'; type: 'bloks' },
  ];
};

export type Blocks = HeroBlockDefinition | GridBlockDefinition | PageBlockDefinition;

export type FieldPlugins = Record<never, never>;

export type Schema = { blocks: Blocks; fieldPlugins: FieldPlugins };

export type Block<TName extends Blocks['name']> = BlockContent<Extract<Blocks, { name: TName }>, Blocks, FieldPlugins>;

export type AnyBlock = BlockContent<Blocks, Blocks, FieldPlugins>;

export type Story = InferStory<Blocks>;
export type StoryMapi = InferStoryMapi<Blocks>;
