// This file was generated by the Storyblok CLI. Do not edit by hand.
// Space: 295018

import type { BlockContent, MapiStory as InferStoryMapi, Schema as InferSchema, Story as InferStory } from '@storyblok/schema';
import type { fieldPlugins as userFieldPlugins } from './plugins';

export type GridBlockDefinition = {
  readonly id: number;
  created_at: string;
  updated_at: string;
  name: 'grid';
  is_root: false;
  is_nestable: true;
  fields: [
    { name: 'columns'; type: 'bloks' },
  ];
};

export type HeroBlockDefinition = {
  readonly id: number;
  created_at: string;
  updated_at: string;
  name: 'hero';
  is_root: false;
  is_nestable: true;
  fields: [
    { name: 'headline'; type: 'text'; required: true },
    { name: 'image'; type: 'asset' },
    { name: 'nested'; type: 'bloks'; allow: ['grid'] },
    { name: 'general'; type: 'tab' },
  ];
};

export type PageBlockDefinition = {
  readonly id: number;
  created_at: string;
  updated_at: string;
  name: 'page';
  is_root: true;
  is_nestable: false;
  fields: [
    { name: 'body'; type: 'bloks' },
    { name: 'accent'; type: 'custom'; field_type: 'colorpicker' },
  ];
};

export type Blocks = GridBlockDefinition | HeroBlockDefinition | PageBlockDefinition;

export type FieldPlugins = InferSchema<{ blocks: Record<string, never>; fieldPlugins: typeof userFieldPlugins }>['fieldPlugins'];

export type Schema = { blocks: Blocks; fieldPlugins: FieldPlugins };

export type Block<TName extends Blocks['name']> = BlockContent<Extract<Blocks, { name: TName }>, Blocks, FieldPlugins>;

export type AnyBlock = BlockContent<Blocks, Blocks, FieldPlugins>;

export type Story = InferStory<Blocks, FieldPlugins>;
export type StoryMapi = InferStoryMapi<Blocks, FieldPlugins>;
