openapi: 3.1.1
info:
  title: Storyblok Links API
  version: 1.0.0
  description: API for delivering Storyblok links
servers:
  $ref: ../shared/servers.yaml
security:
  $ref: ../shared/security.yaml
paths:
  /v2/cdn/links:
    get:
      operationId: getAll
      summary: Retrieve Multiple Links
      description: Returns a map of all links. The API response can be filtered using the query parameters.
      parameters:
        - name: version
          in: query
          required: false
          description: Version to retrieve
          schema:
            type: string
            enum:
              - published
              - draft
            default: published
        - name: cv
          in: query
          required: false
          description: Cached version Unix timestamp for cache invalidation
          schema:
            type: integer
        - name: starts_with
          in: query
          required: false
          description: Filter by path to only return links starting with the given value
          schema:
            type: string
        - name: with_parent
          in: query
          required: false
          description: Include parent link information (1 to enable)
          schema:
            type: integer
        - name: include_dates
          in: query
          required: false
          description: Include published_at, created_at, updated_at fields (0 or 1)
          schema:
            type: integer
            enum:
              - 0
              - 1
        - name: paginated
          in: query
          required: false
          description: Legacy pagination parameter for spaces created before May 9th 2023 (0 or 1)
          schema:
            type: integer
            enum:
              - 0
              - 1
        - name: page
          in: query
          required: false
          description: Page number for pagination
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          required: false
          description: Number of links per page (max 1000)
          schema:
            type: integer
            default: 25
            maximum: 1000
      responses:
        '200':
          description: Map of links
          headers:
            $ref: ../../shared/pagination.yaml#/pagination_headers
          content:
            application/json:
              schema:
                type: object
                required:
                  - links
                properties:
                  links:
                    type: object
                    description: Map of link objects keyed by UUID
                    additionalProperties:
                      $ref: '#/components/schemas/Link'
                  cv:
                    type: integer
                    description: Cache version Unix timestamp
        '400':
          description: Bad request
        '401':
          description: Unauthorized
components:
  securitySchemes:
    $ref: ../shared/security-schemes.yaml#/securitySchemes
  schemas:
    Link:
      $ref: ../shared/links/link-capi.yaml
