// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext } from '../storyblok.d.ts';

export interface CMSFeature {
  name?: string;
  component: 'feature';
  _uid: string;
}

export interface CMSGrid {
  columns?: (CMSFeature | CMSGrid | CMSPage | CMSTeaser | CMSTestWith | CMSTestWithStrangeCasing)[];
  component: 'grid';
  _uid: string;
}

export interface CMSPage {
  body?: (CMSFeature | CMSGrid | CMSPage | CMSTeaser | CMSTestWith | CMSTestWithStrangeCasing)[];
  component: 'page';
  _uid: string;
}

export interface CMSTeaser {
  headline?: string;
  loco: string;
  test?: string;
  customF?: unknown;
  richi?: StoryblokRichtext;
  component: 'teaser';
  _uid: string;
}

export interface CMSTestWith {
  component: 'test with 👋🏼';
  _uid: string;
}

export interface CMSTestWithStrangeCasing {
  component: 'test_With-strangeCasing';
  _uid: string;
}
