name: Publish Any Commit
on:
  push:
    branches:
      - '**'
    tags:
      - '!**'

env:
  HUSKY: 0 # Bypass husky commit hook for CI

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - run: npx pkg-pr-new publish --compact